### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by Citrus216**
dockerized frontend and backend. uses localhost instead of network config (e.g. localhost:3002 instead of backend:3002)
Made some changes necessary for npm run build to complete successfully

### CODE REVIEW

**Review by nguyenvothuan — APPROVED** [review]
Perfect John, would love to see you use volume in the docker compose to see real update when we adding code, instead of rebuilding the docker images over again.

**Comment by Citrus216** [comment]
How do volumes help with hot refreshes? I don't think putting up-to-date code in containers while they are running is as simple as mounting a volume, is it?

**Comment by Citrus216** [comment]
Or do you mean to store the code in a volume when building/composing and then run the code from the volume?

**Comment by Citrus216** [comment]
I see what you mean now. I will mount relevant directories as volumes on their respective containers so we can update the code dynamically. Do you know if that will mandate a change to the dockerfiles at all? It seems like it will but I'll do more research

**Comment by Citrus216** [comment]
@nguyenvothuan I added a volume to allow frontend hot-refreshing, but the backend still requires a rebuild of the image. I couldn't figure out a good way of getting the backend to work without reorganizing the directory structure somewhat.

**Pull request merged**
